<body>

<div id="titleBox"><?php $this->image('title.png'); ?></div>

<div id="mainBox">
	<table border=0 width="100%" height="100%">
		<tr>
			<td width="50%">
				<div id="logoBox">
					<table width="100%" height="100%">
						<tr>
							<td>
								<?php $this->image('logo.png', Array('type'=>'usr', 'width'=>'128', 'height'=>'128')); ?><br>
							</td>
							<td style="font-weight: normal">
								<b>Welcome on EnsKa Core Manager !</b><br><br>
								<i>You must have rights to login in the manager.
							</td>
						</tr>
					</table>
				</div>
			</td>
			<td width="50%">
				<?php
					if ($this->get('error') != "") {
						echo '
							<center>
								<div id="alertBox">
									<table>
										<tr>
											<td>'
												.$this->image('cross.png', Array('type'=>'usr', 'width'=>'16', 'height'=>'16')).
											'</td>
											<td>'.
												$this->get('error')
											.'</td>
										</tr>
									</table>
								</div>
								<br><br>
							</center>
						';
					}
				?>
				<div id="loginBox">
					<form action="?act=signin" method="POST">
						<table>
							<tr>
								<td>
									<i>Login :</i>
								</td>
								<td>
									<input type="text" name="usrLogin" class="textbox">
								</td>
								<td>
									<?php $this->image('user_login.png', Array('type'=>'usr', 'width'=>'16', 'height'=>'16')); ?>
								</td>
							</tr>
							<tr>
								<td>
									<i>Password :</i>
								</td>
								<td>
									<input type="password" name="usrPasswd" class="textbox">
								</td>
								<td>
									<?php $this->image('lock_green.png', Array('type'=>'usr', 'width'=>'16', 'height'=>'16')); ?>
								</td>
								<td>
									<input type="submit" value="Login">
								</td>
							</tr>
						</table>
					</form>
				</div>
			</td>
		</tr>
	</table>
</div>
<br><br><br>
<center>
	<span style="font-weight: normal;">
		Powered by <a href="http://www.enska-system.com/enska/core/">EnsKa Core</a><br>
		&copy 2008 - <?php echo date('Y'); ?>. All rights reserved.
	</span>
</center> 



</body>
</html>