if (obj.id == "win-newRule")
{
	var conn = new Ext.data.Connection();

	var newRuleWizard = {
		xtype:'tabpanel',
		plain: false,
		activeTab: 0,
		height:235,
		deferredRender: false,
		defaults:{bodyStyle:'padding:0px'},
		items: [ {
				title:'Rule informations',
				id: 'new-rule-informations-form',
				iconCls:'icon-infos',
				layout:'form',
				xtype: 'form',
				html: '<div style="padding: 5px; background: whie; color: royalblue; font-size: 20px; font-weight: bold; width: 128px; height: 128px; top: -140px; left: -200px; position: relative;"><img src="<?php echo $this->get('img')?>rules_add_b.png" width=128 height=128></div>',
				defaults: {width: 230},
				bodyStyle: 'padding-left: 230px; padding-top: 60px;',
				items: [ {
						id:'new-rule-ruleName',
						fieldLabel: 'Rule name',
						anchor:'95%',
						xtype: 'textfield',
						minLength: 3,
						maxLength: 20,
						minLengthText: 'Rule name must be at least 3 characters long.',
						maxLengthText: 'Rule name must not be bigger than 20 characters long.',
						blankText: 'You must give a rule name',
						allowBlank:false
					},
					new Ext.form.TextArea ( {
							id:'new-rule-ruleDescription',
							wrap:'on',
							anchor:'95%',
							fieldLabel: 'Description',
						}
					)
				]
			}
		],
		buttons: [ {
				text: 'Save',
				id: 'new-rule-save-btn',
				handler: function() {
					var ruleName = Ext.get('new-rule-ruleName').dom.value;
					var	ruleDescription = Ext.get('new-rule-ruleDescription').dom.value;
					
					msgWait('EnsKa Core is creating the new rule ' + ruleName +'...');
					
					var req = conn.request ( {
							url: '?act=execPlg&plg=newRule',
							method: 'POST',
							params: "data=" + 'create::' + ruleName + '::' + ruleDescription,
							success: function(resObj) {
								if (resObj.responseText == 'success') {
									msgOk('The rule ' + ruleName + ' has been created !');
									winNewRule.close();
								}
								else {
									msgError(resObj.responseText);
								}
							}
						}
					);
				}
			}, {
				text: 'Cancel',
				handler: function() {
					winNewRule.close();
				}
			}
		]
	};

	var winNewRule = new Ext.Window
	( {
			closeAction: 'close',
			layout: "fit",
			modal: true,
			resizable: false,
			closable: true,
			title: "Create a new rule",
			width: 625,
			height: 320,
			border: false,
			items: [
				newRuleWizard
			]
		}
	);
	
	winNewRule.show();
}
