
<div id="manageLogs-content" style="padding: 10px;">
	<br>
	<fieldset id="fs"><legend><img src="<?php echo $this->get('img')?>address-book.png" width="16" height="16"> Logs settings :</legend>
		<table cellspacing="5">
			<tr>
				<td><h5>Status :</h5></td>
				<td>
					<select id="status-logs">
						<option value="disable">Disable</option>
						<option value="enable">Enable</option>
					</select>
				</td>
			</tr>
			<tr>
				<td><h5>Max log file size :</h5></td>
				<td>
					<table>
						<tr>
							<td><input type="text" size="2" id="size-logs"></td>
							<td><small>Mo</small></td>
						</tr>	
					</table>
				</td>
			</tr>
			<tr>
				<td><h5>Log filename :</h5></td>
				<td><input type="text" id="name-logs" size="30"></td>
			</tr>
			<tr>
				<td><h5>Logs path :</h5></td>
				<td><?php echo $this->get('logs_path');?><input type="text" id="folder-logs" size="50"></td>
			</tr>
			<tr>
				<td valign="top"><h5>Log types :</h5></td>
				<td>
					<table>
						<tr>
							<td><input type="checkbox" id="t-error-logs" value="E_ERROR"> E_ERROR</td>
							<td>&nbsp;&nbsp;&nbsp;</td>
							<td><input type="checkbox" id="t-warning-logs" value="E_WARNING"> E_WARNING</td>
							<td>&nbsp;&nbsp;&nbsp;</td>
							<td><input type="checkbox" id="t-parse-logs" value="E_PARSE"> E_PARSE</td>
							<td>&nbsp;&nbsp;&nbsp;</td>
							<td><input type="checkbox" id="t-notice-logs" value="E_NOTICE"> E_NOTICE</td>
						</tr>
						<tr>
							<td><input type="checkbox" id="t-strict-logs" value="E_STRICT"> E_STRICT</td>
							<td>&nbsp;&nbsp;&nbsp;</td>
							<td><input type="checkbox" id="t-deprecated-logs" value="E_DEPRECATED"> E_DEPRECATED</td>
						</tr>
						<tr>
							<td><input type="checkbox" id="t-all-logs" value="E_ALL"> E_ALL</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td><h5>Display errors :</h5></td>
				<td><input type="checkbox" id="display-logs" value="enable"> <small>(for developpment enviroment only)</small></td>
			</tr>
			<!-- <tr>
				<td><h5>Audit :</h5></td>
				<td>
					<table>
						<tr>
							<td>
								<select id="audit-logs">
									<option value="disable">Disable</option>
									<option value="enable">Enable</option>
								</select>
							</td>
							<td><small>(only for the manager)</small></td>
						</tr>
					</table>
				</td>
			</tr> -->
		</table>
	</fieldset>
	<br><br>
</div>