if (obj.id == "win-systemBackup")
{
	var systemBackupWizard =  {
		plain: false,
		height:235,
		deferredRender: false,
		id: 'system-backup-informations-form',
		layout:'form',
		xtype: 'form',
		html: '<table><tr><td><div style="padding: 5px; background: white; color: royalblue; font-size: 16px; font-weight: bold; height: 128px; top: -30px; left: -200px; position: relative;"><img src="ressources/sites/manager/index/images/save_black_b.png" width=128 height=128></div></td>'
				+ '<td><div style="padding: 5px; color: royalblue; font-size: 18px; font-weight: bold; height: 128px; top: 20px; left: -70px; position: relative;">Not available on preview system version!</div></td></tr></table>',
		defaults: {width: 230},
		bodyStyle: 'padding-left: 230px; padding-top: 40px;',
		buttons: [ {
				text: 'Close',
				handler: function() {
					winSystemBackup.close();
				}
			}
		]
	};

	var winSystemBackup = new Ext.Window ( {
			closeAction: 'close',
			layout: "fit",
			modal: true,
			resizable: false,
			closable: true,
			title: "System backup",
			width: 800,
			height: 230,
			border: false,
			items: [
				systemBackupWizard
			]
		}
	);
	winSystemBackup.show();
}